name: "run tests"

on:
    push:
    pull_request:

permissions:
    contents: write

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build:
        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]

        steps:
            -   name: checkout repository
                uses: actions/checkout@v4

            -   name: setup go for extra filepath test
                uses: actions/setup-go@v6
                with:
                    go-version: 'stable'

            -   name: set up (linux)
                if: runner.os == 'Linux'
                run: |
                    sudo apt update
                    sudo apt install -y cmake ninja-build build-essential nasm
                    sudo apt install software-properties-common -y
                    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
                    sudo apt install gcc-14 g++-14 -y
                    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 140 --slave /usr/bin/g++ g++ /usr/bin/g++-14

            -   name: set up (macos)
                if: runner.os == 'macOS'
                run: |
                    brew install cmake ninja llvm nasm
                    sudo xcode-select --install || true
                    echo "PATH=$(brew --prefix llvm)/bin:$PATH" >> $GITHUB_ENV
                    echo "LDFLAGS=-L$(brew --prefix llvm)/lib" >> $GITHUB_ENV
                    echo "CPPFLAGS=-I$(brew --prefix llvm)/include" >> $GITHUB_ENV
                    echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV

            -   name: set up (windows)
                if: runner.os == 'Windows'
                run: |
                    winget install Kitware.CMake Ninja-build.Ninja --silent --accept-source-agreements --accept-package-agreements

            -   name: set up msvc
                if: runner.os == 'Windows'
                uses: TheMrMilchmann/setup-msvc-dev@v4
                with:
                    arch: x64

            -   name: config cmake (windows/linux)
                if: runner.os != 'macOS'
                run: |
                    cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja -B cmake-build-debug

            -   name: config cmake (macos)
                if: runner.os == 'macOS'
                run: |
                    export CC=$(brew --prefix llvm)/bin/clang
                    export CXX=$(brew --prefix llvm)/bin/clang++
                    cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja -B cmake-build-debug -DCMAKE_OSX_SYSROOT=$SDKROOT

            -   name: build
                run: |
                    cmake --build cmake-build-debug

            -   name: run tests
                # continue-on-error: ${{ runner.os != 'Windows' }}
                run: |
                    ctest --test-dir cmake-build-debug --output-on-failure